### ISSUE TITLE
Crash on Editor Shutdown (5.1)

### ISSUE THREAD

**Issue by Grimicus** [fpwong/BlueprintAssistWiki#103]
I was getting an error whenever I shutdown that was complaining about TimerInfoAllocator being invalid. I saw someone suggest turning on -stompmalloc and I found the problem.  In FBlueprintAssistModule::ShutdownModule(), several of the objects it references are stale while trying to shutdown the module.

Repro is pass -stompmalloc on editor start.  Open up a blueprint in the editor and then close the editor.  stompmalloc will report the issues.

Update: I fixed the issues locally and didn't get rid of the TimerInfoAllocator issue. :'( so, I guess it's a low priority lol

**Comment by fpwong** [comment]
Hi thanks for letting me know. stompmalloc seems very useful for debugging. I am not that familiar with debugging / solving these kind of issues. 

So to make sure we are on the same page, I encountered 2 stale references both when shutting down the module:

1. When accessing the `UBASettings::StaticClass->GetName` with `PropertyEditorModule->UnregisterCustomClassLayout`. I fixed this by saving the FName instead of accessing the UBASetting again.
2. When accessing the `RootObject ptr` with `RootObject->Cleanup()`

Simply checking if the RootObject ptr was null is not good enough and I couldn't find a way to check if a raw ptr or TObjectPtr is stale. The solution I found is to replace it with a TWeakObjectPtr but I still need to test if there will be any side effects from doing so. Is this what you did to resolve this?

**Comment by Grimicus** [comment]
yes, that's what I did!  Since you added it to the root, it probably won't be an issue with weak pointer, it just helps to detect when the system deletes it out from under you. :)
