### ISSUE TITLE
Sometimes lines are not straight, for no apparent reason

### ISSUE THREAD

**Issue by Ares9323** [fpwong/BlueprintAssistWiki#105]
Hi, I have recently bought your plugin and I think it's great!
I'm wondering if I am doing something wrong because sometimes the "Ctrl+R" or "F" auto align is not doing what it should do (or at least what I think it should do), here are a few examples of what I'm talking about:

![8qTAZ9jqMq](https://user-images.githubusercontent.com/46932745/207119565-43c4ae91-69c7-471d-9022-a6138c19fd5c.png)

![siQRXKzwyw](https://user-images.githubusercontent.com/46932745/207119574-5b8b0bf3-01f3-40d1-b31c-4d7a9aa31925.png)

![ToigxdgZVH](https://user-images.githubusercontent.com/46932745/207119584-a65ded55-9df8-4f1d-b7e7-8aa03fba3c66.png)

![vaLGvnJy2T](https://user-images.githubusercontent.com/46932745/207119589-fd4c3dda-f1d5-4269-bb0c-588f87eb8152.png)

Thank you in advance, have a great day!

**Comment by fpwong** [comment]
Hi Ares, this looks like an issue with detecting the node size. Try selecting all the nodes in the event and pressing `CTRL+SHIFT+R`. You can read about why this happens here: https://github.com/fpwong/BlueprintAssistWiki/wiki/FAQ#formatting-looks-off

I have improved this since I wrote that FAQ, the plugin is better at detecting when to auto refresh node sizes. I recently fixed the 3rd case in the update a couple days ago, which was due to changing event replication. I'll see why it's not working for the other cases.
