### ISSUE TITLE
Format All incorrectly moves events created with Bind Event nodes, leaving wide gaps between all the other nodes and stretching comments

### ISSUE THREAD

**Issue by alfredbaudisch** [fpwong/BlueprintAssistWiki#117]
- UE 5.1, Auto Size Comments and Blueprint Assist

Those are my nodes before formatting (in the `Event Graph`, not inside a function):

![imagen](https://user-images.githubusercontent.com/248383/225088047-8856ab63-8c01-4e19-a2b1-2de69e59fb92.png)

After formatting with `CTRL+R` this is what happens:

![imagen](https://user-images.githubusercontent.com/248383/225087549-2d8f2d27-0f5c-4c10-8601-3fec59753887.png)

How to avoid the situation at the bottom?

**Comment by alfredbaudisch** [comment]
I can see what happens now, it's because of Event alignment:

![imagen](https://user-images.githubusercontent.com/248383/225090030-18c5ab85-eeaa-4216-8d1f-1c72177f17f9.png)

Tried to tweak these, but still got the same result:

![imagen](https://user-images.githubusercontent.com/248383/225091017-fb95153a-eff1-45fd-a55f-7497b6817f0a.png)

**Comment by alfredbaudisch** [comment]
Changing Format All Style "Node Type (columns by node type)" makes it even worse, it overlaps comments and also push the event to the right.

![imagen](https://user-images.githubusercontent.com/248383/225092985-b4e5693b-40cb-4f15-bb72-ac7ad350633d.png)

**Comment by alfredbaudisch** [comment]
UPDATE:

Changing the output of Bind Event to Create Event solves it, but then `Create Event` keeps stuck to `Bind Event`. Tried many config settings and it just stays like that.

![imagen](https://user-images.githubusercontent.com/248383/225100069-a09dfb6d-d88e-46c2-8f5c-b2d108dc0519.png)

**Comment by fpwong** [comment]
Hi @alfredbaudisch, thanks for the detailed screenshots. If you prefer the initial style (without requiring a `CreateEvent` node) you can enable the setting `Treat Delegates As Execution Pins`.

The issue in the last screenshot can be fixed by refreshing the node size of the `CreateEvent` node. You can do this by selecting the `CreateEvent` node and pressing `CTRL + SHIFT + R`. This is a bug and will be fixed in the next update so it will automatically detect that the node size has changed.

Let me know if this fixed the issue.

**Comment by alfredbaudisch** [comment]
> you can enable the setting `Treat Delegates As Execution Pins`.

That solved it, thanks!

Another one:

Sometimes, depending on zoom level, a comment like this:

![imagen](https://user-images.githubusercontent.com/248383/225569422-76f03d74-125f-4a15-90ce-473e187e3ea5.png)

...after formatting gets like this, so I have always to manually reposition the nodes:
![imagen](https://user-images.githubusercontent.com/248383/225569335-2a0b8b8a-47f0-4566-b9e5-b343ebe61cb2.png)

Any tip/solution for this?

**Comment by fpwong** [comment]
I'm guessing you have the setting `Resizing Mode` set to `Reactive` in the AutoSizeComments plugin? If not let me know. 

So as you can see this setting has issue with zoom level, since it snapshots the node size at the current zoom level. If you are zoomed out it will be extremely off when you zoom back in, like in your example. To ensure the size is accurate you want to be as close to 1:1 zoom level.

The alternate option is that you set the `Resizing Mode` to `Disabled` and let BlueprintAssist handle resizing the comments. Which it will do when formatting.

If you are not using source control you can also set the `Resizing Mode` to `Always` but you definitely should not use it if you have source control since it will cause changes any time you zoom in / out.

**Comment by alfredbaudisch** [comment]
Thanks again, Resizing Mode as `Disabled` solved it.

> If you are not using source control you can also set the Resizing Mode to Always but you definitely should not use it if you have source control since it will cause changes any time you zoom in / out.

Good to know, definitely not going to use `Always`.
