### ISSUE TITLE
Better focus search box searching

### ISSUE THREAD

**Issue by alexander-clarke** [fpwong/BlueprintAssistWiki#118]
![image](https://user-images.githubusercontent.com/9615373/227729217-8f679803-61a3-420f-b53e-cf5eb3d942d0.png)

If I type in world outliner, the search box for world outliner disappears. This is because we are using the default text of the search box as the only way of searching for the search box. If we could also search by the name of the their window that the search boxes in that would be a lot better. This is particularly for some boxes like the world outliner which does not have a useful default text in its search box.

**Comment by fpwong** [comment]
Thanks for letting me know about this. I've swapped around the priorities of the text in the search. Also this functionality is currently broken in 5.2 for some search boxes. Looks like they have changed the widgets in some of the search boxes so they don't get detected anymore.

This will be fixed in the next update.

**Comment by fpwong** [comment]
Fixed in 4.1.6
