### ISSUE TITLE
Comment blocks overlapping

### ISSUE THREAD

**Issue by wickerman123** [fpwong/BlueprintAssistWiki#125]
I'm using BlueprintAssist alongside AutoSizeComments and I have an issue where some comment blocks don't get formatted correctly and end up overlapping when using the FormatAll command:
![strwinclt_Q49sDdRF6e](https://github.com/fpwong/BlueprintAssistWiki/assets/5807444/68925f45-dd1e-4eae-9f61-1017ec2fe6a3)

I'm not sure how to repro this but it does happen frequently. I've tried adjust settings of both plugins but can't find any desirable results. I've also tried clearing caches and restarting but there's no change in behaviour.

**Comment by fpwong** [comment]
Hi @wickerman123, I have just tested this and I can replicate this issue. It appears this is due to the comment padding causing it to mess up the columns. For now I suggest you increase the format all spacing to at least 400 units in the x-axis to be safe.

As 5.2 just came out I have to submit an update asap, so I won't be able to get the fix for this and #124 into the upcoming update. But I'll make sure to fix it in the update after.

**Comment by fpwong** [comment]
Fixed in 4.2.0
