### ISSUE TITLE
Plugin for Unreal Engine 5.2 Linux compatibility issues

### ISSUE THREAD

**Issue by SomeUser9** [fpwong/BlueprintAssistWiki#131]
Hi, I've attempted to run the command below to run the plugin for Linux:
<PATH TO UE>/Engine/Build/BatchFiles/RunUAT.sh BuildPlugin -Plugin=<path to .uplugin> -Package=<output path for compiled plugin>
with the content in between the <> replaced by the actual paths, and I got errors, which I provided the logs for below
[Terminal.txt](https://github.com/fpwong/BlueprintAssistWiki/files/11649755/Terminal.txt)
[UBT-UnrealEditor-Linux-Development.txt](https://github.com/fpwong/BlueprintAssistWiki/files/11649756/UBT-UnrealEditor-Linux-Development.txt)

I've tried the same command on other plugins which worked for about half of them, I was wondering if this issue is due to something on my side as I complied the engine from source code or if the command isn't typed properly

Really hoping the plugin works again because it is my favorite plugin to use for coding in blueprint, so many amazing and convenient utilities that it is hard to do without
Sincerely,
Some User

**Comment by fpwong** [comment]
Hi, yes sorry about any build errors on Linux. I don't have a machine setup to test this. I submit the plugin to the marketplace and as them to build for windows / mac / linux and check if they have any build errors.

Since these errors do not appear on the marketplace side, I'd suspect they (maybe?) have some special build settings to ignore some of these errors due to the differences between building on different platforms.

Regardless, I will try my best to fix the errors here but I may miss some since I am unable to check the build results.

Also just to make sure, are you able to install the plugin through the marketplace for a regular engine build?

**Comment by SomeUser9** [comment]
Hi,
Thank you for the fast reply, currently the epic games launcher does not have linux support, so I'm currently using the windows version on Lutris to be able to browse and purchase content from the marketplace on a Linux and I'm using https://github.com/AchetaGames/Epic-Asset-Manager to download them to a specific folder

I tried to download the plugin from epic games launcher on Lutris into a windows UE 5.2 engine, then tried building that plugin into the linux UE 5.2 and I think I got more errors, here are the logs:

[UBT-UnrealEditor-Linux-Development.txt](https://github.com/fpwong/BlueprintAssistWiki/files/11652085/UBT-UnrealEditor-Linux-Development.txt)

[Terminal.txt](https://github.com/fpwong/BlueprintAssistWiki/files/11652084/Terminal.txt)

Thank you for your time,
sincerely,
Some User

**Comment by fpwong** [comment]
Will be fixing these errors but some searches lead to these posts:

* https://stackoverflow.com/questions/16939888/why-does-clang-warn-within
* https://stackoverflow.com/questions/15053776/how-do-you-disable-the-unused-variable-warnings-coming-out-of-gcc-in-3rd-party-c

Essentially these you should be able to disable these errors without issue using the build args: `-Wno-logical-op-parentheses` and `-Wno-unused-variable`

I would suggest leaving `-Wno-unused-variable` for your own projects just for keeping your code clean.

Alternatively you can also disable showing warnings as errors due to `-Werror` (see [this post](https://stackoverflow.com/questions/2414242/how-can-i-disable-fail-on-warning-when-using-gcc-and-make)).

Hopefully this fixes your issues with other plugins. If you do this for BlueprintAssist right now, there should be 1 remaning error related to `Core/Public/HAL/PlatformFilemanager.h` which simply needs a capital M like so: `Core/Public/HAL/PlatformFileManager.h`.

**Comment by SomeUser9** [comment]
Thank you very much for the reply, 
although I'm not familiar with the code of Unreal Engine, I'm not exactly sure where I should insert those arguments and how, without potentially causing further issues 
Also, after looking in my engine files, the Core/Public/HAL/PlatformFileManager.h does exist and there isn't one with a lower case m, is the lower case in the plugin's code?
Again thank you for dedicating your time for this
sincerely,
Some User

**Comment by fpwong** [comment]
> I'm not exactly sure where I should insert those arguments and how, without potentially causing further issues

Sorry I can't really help here since I do not have Linux setup and am not familiar with building Unreal on there.

---

Perhaps it is best to double check your build works with the fixes implemented. I have sent you an invite to the source repo where I have pushed the changes to fix the errors in your log. You can just pull the latest commit in the main branch.

Let me know if you have any trouble with building from the repo code.

> Also, after looking in my engine files, the Core/Public/HAL/PlatformFileManager.h does exist and there isn't one with a lower case m, is the lower case in the plugin's code?

Yes the issue was that I was using the lower case m when it should be upper case but this didn't cause any build errors on my windows machine.

**Comment by SomeUser9** [comment]
Building the repo code worked successfully, there was no errors!
I can't wait to use the plugin!
Now I just need to figure out why Unreal Editor no longer starts up, once it works again I'll write down everything that was done

**Comment by fpwong** [comment]
Did including the plugin cause your Unreal to not start up, or is this an unrelated issue?

**Comment by SomeUser9** [comment]
Alright, everything was sorted out, the plugin compiled successfully thanks to the repo code, the engine works again, the issue was unrelated to the plugin

Here are the notes I took so that I could follow them later once I need to compile plugins again

[how to fix compiling errors for plugins.txt](https://github.com/fpwong/BlueprintAssistWiki/files/11702932/how.to.fix.compiling.errors.for.plugins.txt)

hopefully it helps out others that stumbled upon this thread

Thanks again for helping out, now I can use your amazing plugin again :D 
sincerely,
Some User

**Comment by fpwong** [comment]
Fixed in 4.2.0
