### ISSUE TITLE
Crash (UE4.23, v2.0.2): when formatting

### ISSUE THREAD

**Issue by tshabi8** [fpwong/BlueprintAssistWiki#14]
![Screenshot 14_12_2019 23_00_27](https://user-images.githubusercontent.com/28268953/70854560-1b623400-1ec6-11ea-87d5-1c9c8108e1fc.png)

[BlueprintassistCrash.zip](https://github.com/fpwong/BlueprintAssistWiki/files/3964345/BlueprintassistCrash.zip)

**Comment by fpwong** [comment]
Hi tshabi8, could you check that this crash still occurs for the new version of the plugin (2.1.0)?

**Comment by kferr** [comment]
I'm getting a crash as well. I know for a fact it's connected with the plugin because when i try to open up the BP, which has the function I'm making open, it instantly crashes. If I instead disable the plugin after reloading my project first then restart to apply the changes, I'm able to open that function with no issues. Swap back to enable the plugin - re-occurring issue.

Blueprint Sample
https://blueprintue.com/render/klmt8o3y

For Reference: the grid space array is an array of vectors 

----
UE Error:
----

LoginId:54458b7548c2564e0dca62a2b9b88afe
EpicAccountId:da901f4911344eb8b48bbb131794cb80

Assertion failed: OwningNode [File:D:\RocketSync\4.24.0-10570792+++UE4+Release-4.24\Working\Engine\Source\Runtime\Engine\Classes\EdGraph/EdGraphPin.h] [Line: 474]

UE4Editor_Core
UE4Editor_Core
UE4Editor_BlueprintAssist!FKnotNodeTrack::GetNodes() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\graphformattertypes.cpp:459]
UE4Editor_BlueprintAssist!FEdGraphFormatter::AddKnotNodesToComments() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\edgraphformatter.cpp:1128]
UE4Editor_BlueprintAssist!FEdGraphFormatter::FormatNode() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\edgraphformatter.cpp:248]
UE4Editor_BlueprintAssist!FBAGraphHandler::FormatNodes() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:1865]
UE4Editor_BlueprintAssist!FBAGraphHandler::UpdateNodesRequiringFormatting() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:1426]
UE4Editor_BlueprintAssist!FBAGraphHandler::Tick() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:437]
UE4Editor_BlueprintAssist!FBATabHandler::Tick() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassisttabhandler.cpp:48]
UE4Editor_BlueprintAssist!FBAInputProcessor::Tick() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistinputprocessor.cpp:318]
UE4Editor_Slate
UE4Editor_Slate
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by kferr** [comment]
> 
> 
> I'm getting a crash as well. I know for a fact it's connected with the plugin because when i try to open up the BP, which has the function I'm making open, it instantly crashes. If I instead disable the plugin after reloading my project first then restart to apply the changes, I'm able to open that function with no issues. Swap back to enable the plugin - re-occurring issue.
> 
> Blueprint Sample
> https://blueprintue.com/render/klmt8o3y
> 
> For Reference: the grid space array is an array of vectors
> 
> Running Blueprint Assist version 2.2.1
> ## UE Error:
> 
> LoginId:54458b7548c2564e0dca62a2b9b88afe
> EpicAccountId:da901f4911344eb8b48bbb131794cb80
> 
> Assertion failed: OwningNode [File:D:\RocketSync\4.24.0-10570792+++UE4+Release-4.24\Working\Engine\Source\Runtime\Engine\Classes\EdGraph/EdGraphPin.h] [Line: 474]
> 
> UE4Editor_Core
> UE4Editor_Core
> UE4Editor_BlueprintAssist!FKnotNodeTrack::GetNodes() [d:\build++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\graphformattertypes.cpp:459]
> UE4Editor_BlueprintAssist!FEdGraphFormatter::AddKnotNodesToComments() [d:\build++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\edgraphformatter.cpp:1128]
> UE4Editor_BlueprintAssist!FEdGraphFormatter::FormatNode() [d:\build++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\edgraphformatter.cpp:248]
> UE4Editor_BlueprintAssist!FBAGraphHandler::FormatNodes() [d:\build++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:1865]
> UE4Editor_BlueprintAssist!FBAGraphHandler::UpdateNodesRequiringFormatting() [d:\build++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:1426]
> UE4Editor_BlueprintAssist!FBAGraphHandler::Tick() [d:\build++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:437]
> UE4Editor_BlueprintAssist!FBATabHandler::Tick() [d:\build++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassisttabhandler.cpp:48]
> UE4Editor_BlueprintAssist!FBAInputProcessor::Tick() [d:\build++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistinputprocessor.cpp:318]
> UE4Editor_Slate
> UE4Editor_Slate
> UE4Editor
> UE4Editor
> UE4Editor
> UE4Editor
> UE4Editor
> kernel32
> ntdll

While having the plugin disabled, I removed the pin of the vector array and then re-enabled the plugin & restarted the project. I was able to open and use the 'F' shortcut key to sort things:

https://blueprintue.com/render/k9q5id9f

I then connected the vector array pin back up to the spawn node and compiled fine. The game runs as expected. As soon as I select everything in that function and press 'F', the crash happens again:


LoginId:54458b7548c2564e0dca62a2b9b88afe
EpicAccountId:da901f4911344eb8b48bbb131794cb80

Assertion failed: OwningNode [File:D:\RocketSync\4.24.0-10570792+++UE4+Release-4.24\Working\Engine\Source\Runtime\Engine\Classes\EdGraph/EdGraphPin.h] [Line: 474]

UE4Editor_Core
UE4Editor_Core
UE4Editor_BlueprintAssist!FKnotNodeTrack::GetNodes() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\graphformattertypes.cpp:459]
UE4Editor_BlueprintAssist!FEdGraphFormatter::AddKnotNodesToComments() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\edgraphformatter.cpp:1128]
UE4Editor_BlueprintAssist!FEdGraphFormatter::FormatNode() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\graphformatters\edgraphformatter.cpp:248]
UE4Editor_BlueprintAssist!FBAGraphHandler::FormatNodes() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:1865]
UE4Editor_BlueprintAssist!FBAGraphHandler::UpdateNodesRequiringFormatting() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:1426]
UE4Editor_BlueprintAssist!FBAGraphHandler::Tick() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistgraphhandler.cpp:437]
UE4Editor_BlueprintAssist!FBATabHandler::Tick() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassisttabhandler.cpp:48]
UE4Editor_BlueprintAssist!FBAInputProcessor::Tick() [d:\build\++portal+promotion\sync\localbuilds\plugintemp\hostproject\plugins\blueprintassist\source\blueprintassist\private\blueprintassistinputprocessor.cpp:318]
UE4Editor_Slate
UE4Editor_Slate
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by kferr** [comment]
Figured out a work around. I made a temp variable in the function to store the result of the other function call. Then I used a get method of that temp variable to assign on the spawn node.

https://blueprintue.com/render/d_wl1tqf

Reminder the GridSpaceArray is a Vector Array.

**Comment by fpwong** [comment]
@kferr Hi kferr, I have a feeling you may not be on the latest version of the plugin (should be 2.2.3). [This issue](https://github.com/fpwong/BlueprintAssistWiki/issues/19) has the same crash log as yours for 2.2.1. You can check the version in the plugins tab. If you are on the latest version, please reply here and I will reopen that issue.

**Comment by kferr** [comment]
You are correct, the Epic client needed an update restart and was blocking
my ability to upgrade to the latest plugin version. Guess I've been at it
for a couple weeks now heh.

I will post back if the issue happens again. Thanks!
