### ISSUE TITLE
[Bug] Property Access Incorrect position after formatting

### ISSUE THREAD

**Issue by millionart** [fpwong/BlueprintAssistWiki#159]
![image](https://github.com/fpwong/BlueprintAssistWiki/assets/7535532/771e1105-bee9-4378-bf98-7dad698b7bcb)

**Comment by fpwong** [comment]
This is likely because the cached node size has been saved incorrectly. For now you will need to manually refresh it by selecting the incorrect nodes (the property access node) and hitting Refresh Node Size `CTRL + SHIFT + R`.

I have fixed this bug in the next issue and property access nodes should automatically detect when they are changed now. Will be included in the next update.

**Comment by millionart** [comment]
It works!
Another little detail in this image is:
The Context to UpdateContext line can actually be connected directly, however after formatting it is moved underneath the Convert to Sequence Evaluator, which creates more line crossings, I have found this problem many times and hopefully can optimize it a bit.

**Comment by fpwong** [comment]
> It works! Another little detail in this image is: The Context to UpdateContext line can actually be connected directly, however after formatting it is moved underneath the Convert to Sequence Evaluator, which creates more line crossings, I have found this problem many times and hopefully can optimize it a bit.

Thanks for pointing this out, added a small change which hopefully fixed this issue too.

**Comment by fpwong** [comment]
Fixed in 4.2.8

**Comment by fpwong** [comment]
Fixed in 4.2.8
