### ISSUE TITLE
Knot nodes causing crash in Control Rig graph when auto formatting in UE 5.3.1

### ISSUE THREAD

**Issue by Jun-ce** [fpwong/BlueprintAssistWiki#177]
# Environment:
UE 5.3.1
Control Rig Graph Editor

# Configuration:
I configured the ControlRigGraph's Exec Pin Name as `RigVMExecuteContext`, which is the 5.3.1's correct name.  It used to be `ControlRigExecuteContext` in 5.0.3.
I am using `Blueprint` formatter type for the control rig graph.  

# Issue:
When auto-formatting creates parameter knots, it will create K2Node's knot, shown in the Blueprint Assist Debug Menu as `K2Node_Knot (K2Node_Knot_18)`.  This causes the RigVM in the control rig editor to crash when compiling due to incorrect casting, and the control rig cannot be successfully compiled.

# Possible solutions:
I tried to manually create a parameter knot node, it shows `ControlRigGraphNode (RerouteNode)` in the debug menu.  I believe this is the correct knot node type that should be automatically created in the control rig graph.  I guess creating the knot node in this type will fix the issue when formatting the control rig graph.  Or add a configuration option for non-blueprint graph that user can choose not to create knot for that type of graph and by default control rig graph won't create knot nodes.

# Note
Also, when I worked with UE 5.0.3, BP Assist won't create any knot nodes in control rig graph, so that I only found this after I upgrade to 5.3.1.

**Comment by fpwong** [comment]
Hi @Jun-ce, the Blueprint formatter type is only for blueprint based graphs. For all other graph types, you will need to use the `Simple` formatter type which doesn't use reroute nodes. The easiest way to tell if you are on a BP graph is if you can make custom events, variables and functions like you do in a normal blueprint.

I suggest you try to remove any generated reroute nodes from formatting because they may cause bugs due to mismatching types.

In the future I hope to eventually add this to the simple formatter but for now the focus is on regular Blueprint graphs.

**Comment by Jun-ce** [comment]
Hi @fpwong , thank you for your answer.  It makes sense.  
The blueprint formatter just looks better for Control Rig, since it's really similar to normal blueprint rather than other simple graphs.  If you can consider adapting the blueprint formatter for a new Control Rig formatter that will be very helpful.  But it's OK to use the simple formatter now.
