### ISSUE TITLE
Parameter of type Append overlaps the node

### ISSUE THREAD

**Issue by Louspirit** [fpwong/BlueprintAssistWiki#40]
Hello,

The parameter node of type _Append_ collapse with the node it is wired to. Same behavior with Helix or Left-side Parameter style.

![image](https://user-images.githubusercontent.com/2952456/122419421-2c907300-cf8b-11eb-9340-8f6c681bcf75.png)

**Comment by fpwong** [comment]
Hi Louspirit, this looks an issue which will be fixed by running the `Refresh Node Size` command. Select the Append Node and press `CTRL+SHIFT+R` to get the correct node size.

You can read more about why this occurs [here](https://github.com/fpwong/BlueprintAssistWiki/wiki/FAQ#formatting-looks-off).

**Comment by Louspirit** [comment]
Sorry. I reopened the graph and it didn't itself. I'll add this to my workflow, thanks.
