### ISSUE TITLE
Unreal acts weird when navigating between functions

### ISSUE THREAD

**Issue by tshabi8** [fpwong/BlueprintAssistWiki#7]
Video attached

[MyProject - Unreal Editor 2019-07-27 21-36-55.zip](https://github.com/fpwong/BlueprintAssistWiki/files/3438473/MyProject.-.Unreal.Editor.2019-07-27.21-36-55.zip)

**Comment by fpwong** [comment]
Hi tshabi8, this is the plugin zooming in on the nodes to cache the size of each node. It needs to do this since the size of nodes changes when you zoom in / out on the graph, so it caches the size at max zoom level.

There is the setting _Cache Size when Required_ in Editor Preferences | Blueprint Assist. This will cause the plugin to do the caching when you format a node instead of doing it when you open the graph.

By default you also format a node whenever you add a node to the graph but there is also a setting to disable this behavior _Automatic Formatting_, so then it will only do the caching when you press the format command.
