### ISSUE TITLE
Unexpected exec knot nodes created when formatting

### ISSUE THREAD

**Issue by Jun-ce** [fpwong/BlueprintAssistWiki#92]
What happened when auto-formatting:
![image](https://user-images.githubusercontent.com/18187396/197886872-69e14083-e9c5-4293-b04d-7f415902d88e.png)

What's expected:
![image](https://user-images.githubusercontent.com/18187396/197886979-7a835031-8c0a-46e0-800b-e1734b13be54.png)

I am not sure if I missed any knot-related settings.  I have tried all but this always exists as long as there is enough height of parameter nodes between two executable nodes.  Disable "Create Knot Nodes" can prevent these unexpected exec knot nodes be created but it also prevents parameter knot nodes.  A possible solution is that separate the setting of "create exec knot nodes" and "create parameter knot nodes".

**Comment by fpwong** [comment]
Ahh this is due to a small change I made to the formatting last patch. Will fix this asap.

**Comment by fpwong** [comment]
On second look, I don't seem to be able to replicate this exact case which causes the bad formatting. Could you try running the command `Refresh Node Size` on all your nodes and see if this fixes this particular issue? You can do this by selecting all the nodes in the function and pressing `CTRL + SHIFT + R`.

**Comment by Jun-ce** [comment]
> On second look, I don't seem to be able to replicate this exact case which causes the bad formatting. Could you try running the command `Refresh Node Size` on all your nodes and see if this fixes this particular issue? You can do this by selecting all the nodes in the function and pressing `CTRL + SHIFT + R`.

No, I have tried this and it didn't work.  Here are my config file and that blueprint.
[BPA_issue.zip](https://github.com/fpwong/BlueprintAssistWiki/files/9881730/BPA_issue.zip)

**Comment by fpwong** [comment]
Hi @Jun-ce, sorry for the late reply. I have submitted a fix for the bug I initially thought was this issue, this should hopefully be out tomorrow.

Unfortunately I was still unable to replicate this exact issue with your settings. However with your settings I had another similar issue where reroute nodes were unexpectedly created. This was fixed by adjusting these settings back to default values:
* `BlueprintKnotTrackSpacing: 26.0` 
* `ParameterVerticalPinSpacing: 26.0`

I'll see what I can do about adjusting these settings so they don't cause issues in the future. Do let me know if this fixed the issue (with / without the new update).

**Comment by Jun-ce** [comment]
Hi @fpwong .  Here are my test results:

Before Update:  Reseting those two values did prevent unexpected exce knots being created.
After Update:  No matter the values of those two parameters, the unexpected exce konts were not created anymore.

Thank you for making this better!
