### ISSUE TITLE
Function Request: Retrieve uppercase input

### ISSUE THREAD

**Issue by 1405100494** [fpwong/BlueprintAssistWiki#96]
Hi!
I hope add a function.
For example the nodes in blender or houdini. They can input the capital letter of the list. Don't need to input all the  words. It's very useful.
Thanks!
![image](https://user-images.githubusercontent.com/72635400/201002901-81e2bd32-3bb6-416e-9d6d-07e207811cbf.png)
![image](https://user-images.githubusercontent.com/72635400/201003056-ad7de3c3-21e0-43a0-9949-92f716c39c44.png)

**Comment by fpwong** [comment]
Hi, coming from Jetbrains IDEs I would also love this feature! I did spend some time trying to implement this for the menus in Blueprint Assist.

The problem is currently there is no way to override the behaviour of the inbuilt engine search algorithm from a plugin. So even if I were to improve the Blueprint Assist search algorithm, it is not very useful since it wouldn't match behaviour of the inbuilt search algorithm.

If you would like to look more into this feature I can only suggest trying to send a pull request on the UE github to support this. The related code is in the file `SGraphActionMenu.cpp`, see function `SGraphActionMenu::GenerateFilteredItems`. However this code is only for the blueprint node creation menu.

**Comment by 1405100494** [comment]
> 嗨，来自 Jetbrains IDE，我也喜欢这个功能！我确实花了一些时间尝试为蓝图助手中的菜单实现这一点。
> 
> 问题是目前无法从插件覆盖内置引擎搜索算法的行为。因此，即使我要改进蓝图助手搜索算法，它也不是很有用，因为它与内置搜索算法的行为不匹配。
> 
> 如果您想更多地了解此功能，我只能建议您尝试在 UE github 上发送拉取请求以支持此功能。相关代码在文件中，请参阅函数。但是，此代码仅适用于蓝图节点创建菜单。`SGraphActionMenu.cpp``SGraphActionMenu::GenerateFilteredItems`

Thanks I try to send it on UE github.
